Full semester 2 planning
demaisj/Epitech-2022-Timeline pull request #1
Opened 2018-01-05 10:06 UTC by Ndr6

Including the following modules:
 - Shell Programming
 - Elementary Programming in C (Part 1 and 2)
 - Unix System Programming
 - Mathematics
 - French Writing Skills
 - C Graphical Programming
 - Introduction to System Administration
 - Introduction to AI
 - Introduction to Networks

2018-01-05 10:07 UTC, Ndr6 commented
Voilà, y'aura plus qu'a merge quand le semestre sera fini ;)

2018-01-06 01:43 UTC, demaisj requested changes
Hello, merci pour ta contribution.
Les projets sont bien organisés par modules, mais ces blocs modules devraient être triés par date du premier projet en ordre croissant, afin de faciliter la lecture de la timeline.
C'est la seule chose à modifier et je peux merge ;)

2018-01-08 08:09 UTC, Ndr6 commented
C'est fait ! C'est vrai que c'est déja plus lisible ^^

2018-01-08 14:04 UTC, demaisj approved these changes

2018-01-08 14:32 UTC, merged